### ISSUE TITLE
Implementing prompt rather than a new component for editing a todo

### ISSUE THREAD

**Issue by Nishant-Pall** [l0609890/pern-todo-app#14]
In between the tutorial, I wanted to give a try to editing the todo using a prompt function instead of calling the EditTodo Component. This is the implementation I could achieve so far
```
const editTodo = async (todoId: number) => {
        let newTodo = prompt("Enter the new todo");
        if (newTodo) {
            try {
                const editTodo = await fetch(
                    `http://localhost:5000/todos/${todoId}`,
                    {
                        method: "PUT",
                        headers: {
                            "Content-type": "application/json",
                        },
                        body: JSON.stringify({
                            description: newTodo,
                        }),
                    }
                );
                getTodos();
                window.location.href = "/";
            } catch (err: any) {
                console.error(err.message);
            }
        }
    };

```
I didn't change anything on the server-side, and apparently, when I edit a todo, it gets edited but moves to the last of the list. I realized this happens even if I'm making the request from postman, is this a Postgres thing? and is there any workaround to avoid this little bug?

Thanks a lot in advance

**Comment by ousecTic** [comment]
Heya @Nishant-Pall ,

Yea this is typical funky behaviour from PostgreSQL, you can easily fix it using `ORDER BY` on the server-side. Just like a `DELETE` and `INSERT`, an `UPDATE` will create a new row version. Here are two StackOverflow posts that should give better guidance. I wish you the best of luck :)

https://stackoverflow.com/questions/52486162/postgresql-table-row-goes-to-the-bottom-when-updating/52486581

https://stackoverflow.com/questions/29573057/prevent-re-ordering-of-updated-objects-rows-in-postgresql-sqlalchemy

Cheers
